---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: hextris
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./fluxcd/components/hextris
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: crds
