name: 'Terraform Destroy - EKS then VPC'

on:
  workflow_dispatch:
    inputs:
      tfvars_file:
        description: 'Path to the .tfvars file for VPC (default: build.tfvars)'
        required: true
        default: 'build.tfvars'

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

permissions:
  contents: read

jobs:
  CheckOut-Repo:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

  Setting-Up-Terraform:
    runs-on: ubuntu-latest
    needs: CheckOut-Repo

    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.4

  Destroy-EKS-Then-VPC:
    runs-on: ubuntu-latest
    needs: Setting-Up-Terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.4

      # Destroy EKS
      - name: Terraform Initialize (EKS)
        working-directory: terraform/eks
        run: terraform init

      - name: Terraform Destroy (EKS)
        working-directory: terraform/eks
        run: terraform destroy -auto-approve -var-file=eks.tfvars -input=false

      # Destroy VPC
      - name: Terraform Initialize (VPC)
        working-directory: terraform/vpc
        run: terraform init

      - name: Terraform Destroy (VPC)
        working-directory: terraform/vpc
        run: terraform destroy -auto-approve -var-file=${{ github.event.inputs.tfvars_file }} -input=false